specVersion: 0.3.0
name: solana-starter
version: 0.0.0
description: >-
  Starter project for Solana
repository: https://github.com/sotatek-dev/subql-solana-starter
schema:
  file: ./schema.graphql
network:
  endpoint: https://ancient-cold-log.solana-mainnet.quiknode.pro/22dca31ccc366ea3d664aeef3c1e1e84e67740b4/
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  # You can add a dictionary below. This dictionary only works when you have "handleTransaction" with filters. "HandBlock" should also be disabled.
  # dictionary: https://solana-dictionary.subql.sotatek.works
dataSources:
  - kind: solana/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: solana/BlockHandler
        - handler: handleTransaction
          kind: solana/TransactionHandler
  ## You can add filters below. Currently, we only support filtering by transaction's status and the programId the transaction has interacted with.
          # filter:
          #   status: Ok #Filter transactions that has "Ok" status. If you want to filter error transactions, use "Err".
          #   programId: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA #Filter transactions that have interacted with "Token Program"
          #   instruction: Burn #Filter transactions that executed "Burn" instruction of "Token Program"